[package]
name = "yueliao11_swap"
version = "0.0.1"

[dependencies]
Sui = { git = "https://gitee.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
mycoin = { local = "../../task2/mycoin" }
faucetcoin = { local = "../../task2/faucetcoin" }

[addresses]
yueliao11_swap = "0x0"
sui = "0x2"
mycoin = "0xc542cb63bd5b818c97a381cc9a9e412f39fc8931ea3b649d56a8ee160feb8809"
faucetcoin = "0x4e4ca0ff3a45ec5a9f81abe87a2c87ca13c95b73a2007eeab1f1d92a5b704e5f"

