[package]
name = "hello_move"
edition = "2024.beta"
publish_at = "0x13679122eabfd92046d140e6261748b0cfeb05e25a7eb7dda626591139062c1a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
hello_move = "0x13679122eabfd92046d140e6261748b0cfeb05e25a7eb7dda626591139062c1a"

[dev-dependencies]

[dev-addresses]
