[package]
name = "task5"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
martinyeung5 = "0x0"

[dev-dependencies]

[dev-addresses]


