import { ConnectButton, useCurrentAccount } from "@mysten/dapp-kit";
import { Box, Flex, Heading } from "@radix-ui/themes";
import NaviPage from "../components/navi";
export default function Home() {
    useCurrentAccount();
    return (
      <>
        <Flex
            position="sticky"
            px="4"
            py="2"
            justify="between"
            style={{
              borderBottom: "1px solid var(--gray-a2)",
            }}
        >
          <Box>
            <Heading>Generated by create next dApp Starter Template</Heading>
          </Box>
          <Box>
            <ConnectButton />
          </Box>
        </Flex>
        <NaviPage />
      </>
  );
}
