[package]
name = "faucetcoin"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://gitee.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
faucetcoin = "0x0"

